source_if_exists () {
	[[ -f "$1" ]] && source "$1"
}

source_if_exists "$XDG_CONFIG_HOME/alias"
source_if_exists "$XDG_CONFIG_HOME/functions/docker-functions"

# Colors
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
    xterm) color_prompt=yes;;
esac

# Pyenv
if command -v pyenv >/dev/null 2>&1; then
	eval "$(pyenv init -)"
fi
